In [1]:
import pandas as pd

In [2]:
# Import data
df09 = pd.read_csv('2009.csv', low_memory=False)
df10 = pd.read_csv('2010.csv', low_memory=False)
df11 = pd.read_csv('2011.csv', low_memory=False)
df12 = pd.read_csv('2012.csv', low_memory=False)
df13 = pd.read_csv('2013.csv', low_memory=False)
df14 = pd.read_csv('2014.csv', low_memory=False)
df15 = pd.read_csv('2015.csv', low_memory=False)
df16 = pd.read_csv('2016.csv', low_memory=False)
df17 = pd.read_csv('2017.csv', low_memory=False)
df18 = pd.read_csv('2018.csv', low_memory=False)

In [3]:
df = pd.concat([df09, df10, df11, df12, df13, df14, df15, df16, df17, df18])
df.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2009-01-01,XE,1204,DCA,EWR,1100.0,1058.0,-2.0,18.0,1116.0,...,62.0,68.0,42.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2009-01-01,XE,1206,EWR,IAD,1510.0,1509.0,-1.0,28.0,1537.0,...,82.0,75.0,43.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2009-01-01,XE,1207,EWR,DCA,1100.0,1059.0,-1.0,20.0,1119.0,...,70.0,62.0,36.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2009-01-01,XE,1208,DCA,EWR,1240.0,1249.0,9.0,10.0,1259.0,...,77.0,56.0,37.0,199.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2009-01-01,XE,1209,IAD,EWR,1715.0,1705.0,-10.0,24.0,1729.0,...,105.0,77.0,40.0,213.0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.shape[0]

61556964